services:
  data_warehouse:
    image: postgres:16
    container_name: data_warehouse
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../datasets:/datasets
networks:
  default:
  data_network:
    external: true